version: '3'
services:
  catalogue-service:
    build: .
    ports:
     - "7071:7071"
    environment:
     - MYSQL_HOST=catalogue-db
     - SC_HOST=sc-host
  catalogue-db:
    build: ./data/
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=developer
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
     - MYSQL_DATABASE=CATALOGUE_DB
  sc-host:
    image: servicecomb/service-center:latest
    ports:
     - "30100:30100"
